import { MapDataType } from '@csegames/library/dist/_baseGame/GameClientModels/AnimationData';

export interface FactionData {
  id: string;
  backgroundBookImage: string;
  backgroundCharacterImage: string;
  backgroundClassIconImage: string;
  backgroundFullscreenImage: string;
  backgroundLeatherImage: string;
  backgroundProgressBarImage: string;
  nameplateIconFrameImage: string;
  abilityBarEmptySlotImage: string;
  nameplateBackgroundImage: string;
  nameplateMainFrameImage: string;
  nameplateMiniFrameImage: string;
  nameplateProfileImage: string;
  paperdollBackgroundImage: string;
  paperdollBaseImage: string;
  factionSelectBackgroundImage: string;
  factionSelectEmblemImage: string;
  unitFrameBackgroundImage: string;
  unitFrameForegroundImage: string;
  unitFrameForegroundTargetImage?: string;
  unitFrameForegroundPartyMemberImage: string;
  unitFrameForegroundPartyLeaderImage: string;
  unitFrameResourceDividerImage: string;
  unitFrameDeterminationPipBorder: string;
  unitFrameJudgementPipBackground: string;
  simpleUnitFrameBackgroundImage?: string;
  simpleUnitFrameForegroundImage?: string;
  simpleUnitFrameForegroundRightImage?: string;
  simpleUnitFrameForegroundPartyMemberImage?: string;
  simpleUnitFrameForegroundPartyLeaderImage?: string;
  abilityBarLeftImage: string;
  abilityBarLeftBlankImage: string;
  abilityBarRightImage: string;
  abilityBarRightBlankImage: string;
  abilityBarCenterFrontImage: string;
  abilityBarCenterBackImage: string;
  abilityBarCenterDecorTopImage: string;
  abilityBarCenterDecorBottomImage: string;
  borderImage: string;
  borderCloseWindowImage: string;
  windowBackgroundImage: string;
  windowCloseImage: string;
  windowLockImage: string;
  windowMaximizeImage: string;
  windowUnlockImage: string;
  windowWindowedImage: string;
  compassNeedleImage: string;
  mapIconImages: Record<MapDataType, string>;
  mapPipImage: string;
  scrollbarImage: string;
  scrollbarShortImage: string;
  miniMapImage: string;
  cornerPrimaryTopLeftImage: string;
  cornerPrimaryTopRightImage: string;
  cornerPrimaryBottomLeftImage: string;
  cornerPrimaryBottomRightImage: string;
  cornerSecondaryTopLeftImage: string;
  cornerSecondaryTopRightImage: string;
  cornerSecondaryBottomLeftImage: string;
  cornerSecondaryBottomRightImage: string;
  cornerDecorativeTopLeftImage: string;
  cornerDecorativeTopRightImage: string;
  cornerDecorativeTopRightEmptyImage: string;
  cornerDecorativeBottomLeftImage: string;
  cornerDecorativeBottomRightImage: string;
  cornerFancyTopLeftImage: string;
  cornerFancyTopLeftHeaderImage: string;
  cornerFancyTopRightImage: string;
  cornerFancyTopRightHeaderImage: string;
  cornerFancyBottomLeftImage: string;
  cornerFancyBottomRightImage: string;
  edgeDecorativeTopImage: string;
  edgeDecorativeLeftImage: string;
  edgeDecorativeRightImage: string;
  edgeDecorativeBottomImage: string;
  edgeFancyTopImage: string;
  headerFancyBookendImage: string;
  borderColor: string;
  targetBorderColor: string;
  squareBackgroundImage: string;
  bagBackgroundImage: string;
  searchBackgroundColor: string;
  hudnavIconGameMenuImage: string;
  hudnavIconWorldMapImage: string;
  hudnavIconEquippedImage: string;
  hudnavIconInventoryImage: string;
  hudnavIconGameInfoImage: string;
  hudnavIconAbilityBookImage: string;
  hudnavIconMailImage: string;
  hudnavIconGuildImage: string;
  hudnavIconQuestLogImage: string;
  hudnavEndImage: string;
  sendButtonImage: string;
  gearSlotImages: {
    gearSlotID: string;
    image: string;
  }[];
  prospectingBackgroundImage: string;
  arrowLeftImage: string;
  arrowPointerImage: string;
  buttonBackgroundImage: string;
  buttonBackgroundMediumImage: string;
  buttonBackgroundSmallImage: string;
  buttonSquareBackgroundImage: string;
  checkboxBackgroundImage: string;
  sliderMiniImage: string;
  goldBackgroundImage: string;
  dividerVerticalImage: string;
  dividerVerticalHalfImage: string;
  dividerVerticalSimpleImage?: string;
  mailDividerColor: string;
  mailSenderColor: string;
  mailMessageBackgroundImage: string;
  mailRowBackgroundImage: string;
  mailRowPaperImage: string;
  // Matches targetBorderColor for TDD/Viking/Arthurian (unified glow color); Factionless intentionally kept separate (black).
  selectionGlowColor: string;
  warbandPartyBackgroundImage: string;
  iconArmorSaleImage: string;
  iconArmorSaleLargeImage: string;
  iconCastleImage: string;
  iconCastleLargeImage: string;
  iconCrownImage: string;
  iconCrownLargeImage: string;
  iconTutorialImage: string;
  iconMiscSaleImage: string;
  iconMiscSaleLargeImage: string;
  iconWeaponSaleImage: string;
  iconWeaponSaleLargeImage: string;
  headerBorderImage: string;
  headerBorderSecondaryImage: string;
  endcapImage: string;
  factionShieldImage: string;
  backgroundRealmVideo: string;
  progressBarImage: string;
  progressBarCircleFillImage: string;
  progressBarCircleBackgroundImage: string;
  flagBlankImage: string;
  taperBarImage: string;
  mapGlobeImage: string;
  // Shared frame art for non-player nameplates: NPCs, resource nodes, and gates.
  universalUnitFrameForegroundImage: string;
  universalUnitFrameBackgroundImage: string;
}

export const allFactionData: FactionData[] = [
  {
    id: 'Factionless',
    backgroundBookImage: '/images/MissingAsset.png',
    backgroundCharacterImage: '/images/MissingAsset.png',
    backgroundClassIconImage: '/images/MissingAsset.png',
    backgroundFullscreenImage: 'dynamic/factions/assets/background-fullscreen-factionless.png',
    backgroundLeatherImage: '/dynamic/factions/assets/background-leather-factionless.png',
    backgroundProgressBarImage: '/images/MissingAsset.png',
    nameplateIconFrameImage: '/images/unit-frames/default-frame.png',
    abilityBarEmptySlotImage: '/images/MissingAsset.png',
    nameplateBackgroundImage: '/images/unit-frames/nameplate-bg.png',
    nameplateMainFrameImage: '/images/MissingAsset.png',
    nameplateMiniFrameImage: '/images/unit-frames/mini-frame.png',
    nameplateProfileImage: '/images/MissingAsset.png',
    paperdollBackgroundImage: '/images/MissingAsset.png',
    paperdollBaseImage: '/images/MissingAsset.png',
    factionSelectBackgroundImage: '/images/MissingAsset.png',
    factionSelectEmblemImage: '/images/MissingAsset.png',
    unitFrameBackgroundImage: '/dynamic/factions/assets/unit-frame-back-factionless.png',
    unitFrameForegroundImage: '/dynamic/factions/assets/unit-frame-front-factionless.png',
    unitFrameForegroundPartyMemberImage: '/images/MissingAsset.png',
    unitFrameForegroundPartyLeaderImage: '/images/MissingAsset.png',
    unitFrameResourceDividerImage: '/images/MissingAsset.png',
    unitFrameJudgementPipBackground: '/images/MissingAsset.png',
    unitFrameDeterminationPipBorder: '/images/MissingAsset.png',
    simpleUnitFrameBackgroundImage: '/dynamic/factions/assets/unit-frame-back-simple-factionless.png',
    simpleUnitFrameForegroundImage: '/dynamic/factions/assets/unit-frame-front-simple-factionless.png',
    simpleUnitFrameForegroundRightImage: '/dynamic/factions/assets/unit-frame-front-simple-right-factionless.png',
    simpleUnitFrameForegroundPartyMemberImage: '/dynamic/factions/assets/unit-frame-front-simple-factionless.png',
    simpleUnitFrameForegroundPartyLeaderImage: '/dynamic/factions/assets/unit-frame-front-simple-factionless.png',
    abilityBarLeftImage: '/images/MissingAsset.png',
    abilityBarLeftBlankImage: '/images/MissingAsset.png',
    abilityBarRightImage: '/images/MissingAsset.png',
    abilityBarRightBlankImage: '/images/MissingAsset.png',
    abilityBarCenterFrontImage: '/images/MissingAsset.png',
    abilityBarCenterBackImage: '/images/MissingAsset.png',
    abilityBarCenterDecorTopImage: '/images/MissingAsset.png',
    abilityBarCenterDecorBottomImage: '/images/MissingAsset.png',
    borderImage: '/images/MissingAsset.png',
    borderCloseWindowImage: '/images/MissingAsset.png',
    windowBackgroundImage: '/images/MissingAsset.png',
    windowCloseImage: '/images/MissingAsset.png',
    windowLockImage: '/images/MissingAsset.png',
    windowMaximizeImage: '/images/MissingAsset.png',
    windowUnlockImage: '/images/MissingAsset.png',
    windowWindowedImage: '/images/MissingAsset.png',
    compassNeedleImage: '/dynamic/factions/assets/compass-needle-factionless.png',
    mapIconImages: {
      [MapDataType.INVALID]: '/images/MissingAsset.png',
      [MapDataType.CraftingAlchemy]: '/dynamic/factions/assets/map-icon-alchemy-station-factionless.png',
      [MapDataType.CraftingArtifice]: '/dynamic/factions/assets/map-icon-artificing-station-factionless.png',
      [MapDataType.CraftingCooking]: '/dynamic/factions/assets/map-icon-cooking-station-factionless.png',
      [MapDataType.CraftingForge]: '/dynamic/factions/assets/map-icon-forge-station-factionless.png',
      [MapDataType.CraftingJewels]: '/dynamic/factions/assets/map-icon-jewelry-station-factionless.png',
      [MapDataType.CraftingLeatherworking]: '/dynamic/factions/assets/map-icon-leather-station-factionless.png',
      [MapDataType.CraftingSmithy]: '/dynamic/factions/assets/map-icon-blacksmithing-station-factionless.png',
      [MapDataType.CraftingTailoring]: '/dynamic/factions/assets/map-icon-textile-station-factionless.png',
      [MapDataType.CraftingWoodworking]: '/dynamic/factions/assets/map-icon-woodworking-station-factionless.png',
      [MapDataType.KeepBank]: '/dynamic/factions/assets/map-icon-personal-bank-factionless.png',
      [MapDataType.KeepMain]: '/dynamic/factions/assets/map-icon-keep-factionless.png',
      [MapDataType.KeepRoyalVendor]: '/dynamic/factions/assets/map-icon-royal-vendor-factionless.png',
      [MapDataType.KeepTowerArmory]: '/dynamic/factions/assets/map-icon-armory-factionless.png',
      [MapDataType.KeepTowerBarrack]: '/dynamic/factions/assets/map-icon-barrack-factionless.png',
      [MapDataType.KeepTowerChurch]: '/dynamic/factions/assets/map-icon-church-factionless.png',
      [MapDataType.KeepTowerStable]: '/dynamic/factions/assets/map-icon-stable-factionless.png',
      [MapDataType.Player]: '/images/MissingAsset.png',
      [MapDataType.PortalLocal]: '/dynamic/factions/assets/map-icon-portal-local-factionless.png',
      [MapDataType.PortalZone]: '/dynamic/factions/assets/map-icon-portal-zone-factionless.png',
      [MapDataType.ResourceEssence]: '/dynamic/factions/assets/map-icon-essence-factionless.png',
      [MapDataType.ResourceFishing]: '/dynamic/factions/assets/map-icon-fishing-factionless.png',
      [MapDataType.ResourceHerbs]: '/dynamic/factions/assets/map-icon-herbs-factionless.png',
      [MapDataType.ResourceHunting]: '/dynamic/factions/assets/map-icon-hunting-factionless.png',
      [MapDataType.ResourceLogging]: '/dynamic/factions/assets/map-icon-logging-factionless.png',
      [MapDataType.ResourceMinerals]: '/dynamic/factions/assets/map-icon-minerals-factionless.png',
      [MapDataType.ResourceMining]: '/dynamic/factions/assets/map-icon-mining-factionless.png',
      [MapDataType.Self]: '/images/MissingAsset.png'
    },
    mapPipImage: '/dynamic/factions/assets/map-icon-tier-pip-factionless.png',
    scrollbarImage: '/images/MissingAsset.png',
    scrollbarShortImage: '/images/MissingAsset.png',
    miniMapImage: '/images/MissingAsset.png',
    cornerPrimaryTopLeftImage: '/images/MissingAsset.png',
    cornerPrimaryTopRightImage: '/images/MissingAsset.png',
    cornerPrimaryBottomLeftImage: '/images/MissingAsset.png',
    cornerPrimaryBottomRightImage: '/images/MissingAsset.png',
    cornerSecondaryTopLeftImage: '/images/MissingAsset.png',
    cornerSecondaryTopRightImage: '/images/MissingAsset.png',
    cornerSecondaryBottomLeftImage: '/images/MissingAsset.png',
    cornerSecondaryBottomRightImage: '/images/MissingAsset.png',
    cornerDecorativeTopLeftImage: '/dynamic/factions/assets/corner-decorative-tl-factionless.png',
    cornerDecorativeTopRightImage: '/dynamic/factions/assets/corner-decorative-tr-factionless.png',
    cornerDecorativeTopRightEmptyImage: '/dynamic/factions/assets/corner-decorative-tr-factionless.png',
    cornerDecorativeBottomLeftImage: '/dynamic/factions/assets/corner-decorative-bl-factionless.png',
    cornerDecorativeBottomRightImage: '/dynamic/factions/assets/corner-decorative-br-factionless.png',
    cornerFancyTopLeftImage: '/images/MissingAsset.png',
    cornerFancyTopLeftHeaderImage: '/images/MissingAsset.png',
    cornerFancyTopRightImage: '/images/MissingAsset.png',
    cornerFancyTopRightHeaderImage: '/images/MissingAsset.png',
    cornerFancyBottomLeftImage: '/images/MissingAsset.png',
    cornerFancyBottomRightImage: '/images/MissingAsset.png',
    edgeDecorativeTopImage: '/dynamic/factions/assets/edge-decorative-top-factionless.png',
    edgeDecorativeLeftImage: '/dynamic/factions/assets/edge-decorative-left-factionless.png',
    edgeDecorativeRightImage: '/dynamic/factions/assets/edge-decorative-right-factionless.png',
    edgeDecorativeBottomImage: '/dynamic/factions/assets/edge-decorative-bottom-factionless.png',
    edgeFancyTopImage: '/images/MissingAsset.png',
    headerFancyBookendImage: '/images/MissingAsset.png',
    borderColor: '#727272',
    targetBorderColor: 'white',
    squareBackgroundImage: '/images/MissingAsset.png',
    bagBackgroundImage: '/images/MissingAsset.png',
    searchBackgroundColor: 'transparent',
    hudnavIconGameMenuImage: '/images/MissingAsset.png',
    hudnavIconWorldMapImage: '/images/MissingAsset.png',
    hudnavIconEquippedImage: '/images/MissingAsset.png',
    hudnavIconInventoryImage: '/images/MissingAsset.png',
    hudnavIconGameInfoImage: '/images/MissingAsset.png',
    hudnavIconAbilityBookImage: '/images/MissingAsset.png',
    hudnavIconMailImage: '/images/MissingAsset.png',
    hudnavIconGuildImage: '/images/MissingAsset.png',
    hudnavIconQuestLogImage: '/images/MissingAsset.png',
    hudnavEndImage: '/images/MissingAsset.png',
    sendButtonImage: '/images/MissingAsset.png',
    gearSlotImages: [],
    prospectingBackgroundImage: '/images/MissingAsset.png',
    universalUnitFrameForegroundImage: '/dynamic/factions/assets/unit-frame-front-universal-factionless.png',
    universalUnitFrameBackgroundImage: '/dynamic/factions/assets/unit-frame-back-universal-factionless.png',
    arrowLeftImage: '/images/MissingAsset.png',
    arrowPointerImage: '/images/MissingAsset.png',
    buttonBackgroundImage: '/images/MissingAsset.png',
    buttonBackgroundMediumImage: '/images/MissingAsset.png',
    buttonBackgroundSmallImage: '/images/MissingAsset.png',
    buttonSquareBackgroundImage: '/images/MissingAsset.png',
    checkboxBackgroundImage: '/images/MissingAsset.png',
    sliderMiniImage: '/images/MissingAsset.png',
    goldBackgroundImage: '/images/MissingAsset.png',
    dividerVerticalImage: '/images/MissingAsset.png',
    dividerVerticalHalfImage: '/images/MissingAsset.png',
    mailDividerColor: '#000000',
    mailSenderColor: '#aaaaaa',
    mailMessageBackgroundImage: '/images/MissingAsset.png',
    mailRowBackgroundImage: '/images/MissingAsset.png',
    mailRowPaperImage: '/images/MissingAsset.png',
    selectionGlowColor: '#000000',
    warbandPartyBackgroundImage: '/images/MissingAsset.png',
    iconArmorSaleImage: '/images/MissingAsset.png',
    iconArmorSaleLargeImage: '/images/MissingAsset.png',
    iconCastleImage: '/images/MissingAsset.png',
    iconCastleLargeImage: '/images/MissingAsset.png',
    iconCrownImage: '/images/MissingAsset.png',
    iconCrownLargeImage: '/images/MissingAsset.png',
    iconTutorialImage: '/images/MissingAsset.png',
    iconMiscSaleImage: '/images/MissingAsset.png',
    iconMiscSaleLargeImage: '/images/MissingAsset.png',
    iconWeaponSaleImage: '/images/MissingAsset.png',
    iconWeaponSaleLargeImage: '/images/MissingAsset.png',
    headerBorderImage: '/images/MissingAsset.png',
    headerBorderSecondaryImage: '/images/MissingAsset.png',
    endcapImage: '/dynamic/factions/assets/endcap-factionless.png',
    factionShieldImage: '/images/MissingAsset.png',
    backgroundRealmVideo: '',
    progressBarImage: '/images/MissingAsset.png',
    progressBarCircleFillImage: '/images/MissingAsset.png',
    progressBarCircleBackgroundImage: '/images/MissingAsset.png',
    flagBlankImage: '/images/MissingAsset.png',
    taperBarImage: '/images/MissingAsset.png',
    mapGlobeImage: '/images/MissingAsset.png'
  },
  {
    id: 'TDD',
    backgroundBookImage: '/dynamic/factions/assets/ability-book-background-tdd.png',
    backgroundCharacterImage: '/dynamic/factions/assets/background-character-tdd.png',
    backgroundClassIconImage: '/dynamic/factions/assets/ability-book-class-icon-background-tdd.png',
    backgroundFullscreenImage: 'dynamic/factions/assets/background-fullscreen-tdd.png',
    backgroundLeatherImage: '/dynamic/factions/assets/background-leather-tdd.png',
    backgroundProgressBarImage: '/dynamic/factions/assets/background-progress-bar-tdd.png',
    nameplateIconFrameImage: '/dynamic/factions/assets/tdd-default-frame.png',
    abilityBarEmptySlotImage: '/dynamic/factions/assets/tdd-empty-slot.png',
    nameplateBackgroundImage: '/dynamic/factions/assets/tdd-nameplate-bg.png',
    nameplateMainFrameImage: '/dynamic/factions/assets/tdd-main-frame.png',
    nameplateMiniFrameImage: '/dynamic/factions/assets/tdd-mini-frame.png',
    nameplateProfileImage: '/dynamic/factions/assets/tdd-propic.png',
    paperdollBackgroundImage: '/dynamic/factions/assets/bg-tdd.png',
    paperdollBaseImage: '/dynamic/factions/assets/tdd-base.png',
    factionSelectBackgroundImage: '/dynamic/factions/assets/faction-select-bg-tdd.jpg',
    factionSelectEmblemImage: '/dynamic/factions/assets/faction-select-emblem-tdd.png',
    unitFrameBackgroundImage: '/dynamic/factions/assets/unit-frame-back-tdd.png',
    unitFrameForegroundImage: '/dynamic/factions/assets/unit-frame-front-tdd.png',
    unitFrameForegroundTargetImage: '/dynamic/factions/assets/unit-frame-front-target-tdd.png',
    unitFrameForegroundPartyMemberImage: '/dynamic/factions/assets/unit-frame-front-party-member-tdd.png',
    unitFrameForegroundPartyLeaderImage: '/dynamic/factions/assets/unit-frame-front-party-leader-tdd.png',
    unitFrameJudgementPipBackground: '/dynamic/factions/assets/unit-frame-judgement-pip-tdd.png',
    unitFrameResourceDividerImage: '/dynamic/factions/assets/unit-frame-resource-divider-tdd.png',
    unitFrameDeterminationPipBorder: '/dynamic/factions/assets/unit-frame-determination-pip-tdd.png',
    simpleUnitFrameBackgroundImage: '/dynamic/factions/assets/unit-frame-back-simple-tdd.png',
    simpleUnitFrameForegroundImage: '/dynamic/factions/assets/unit-frame-front-simple-tdd.png',
    simpleUnitFrameForegroundRightImage: '/dynamic/factions/assets/unit-frame-front-simple-right-tdd.png',
    simpleUnitFrameForegroundPartyMemberImage: '/dynamic/factions/assets/unit-frame-front-simple-tdd.png',
    simpleUnitFrameForegroundPartyLeaderImage: '/dynamic/factions/assets/unit-frame-front-simple-tdd.png',
    abilityBarLeftImage: '/dynamic/factions/assets/ability-bar-left-tdd.png',
    abilityBarLeftBlankImage: '/dynamic/factions/assets/ability-bar-left-blank-tdd.png',
    abilityBarRightImage: '/dynamic/factions/assets/ability-bar-right-tdd.png',
    abilityBarRightBlankImage: '/dynamic/factions/assets/ability-bar-right-blank-tdd.png',
    abilityBarCenterFrontImage: '/dynamic/factions/assets/ability-bar-center-front-tdd.png',
    abilityBarCenterBackImage: '/dynamic/factions/assets/ability-bar-center-back-tdd.png',
    abilityBarCenterDecorTopImage: '/dynamic/factions/assets/ability-bar-center-decor-top-tdd.png',
    abilityBarCenterDecorBottomImage: '/dynamic/factions/assets/ability-bar-center-decor-bottom-tdd.png',
    borderImage: '/dynamic/factions/assets/border-tdd.png',
    borderCloseWindowImage: '/dynamic/factions/assets/border-close-window-tdd.png',
    windowBackgroundImage: '/dynamic/factions/assets/window-background-tdd.jpg',
    windowCloseImage: '/dynamic/factions/assets/window-close-tdd.png',
    windowLockImage: '/dynamic/factions/assets/window-lock-tdd.png',
    windowMaximizeImage: '/dynamic/factions/assets/window-maximize-tdd.png',
    windowUnlockImage: '/dynamic/factions/assets/window-unlock-tdd.png',
    windowWindowedImage: '/dynamic/factions/assets/window-windowed-tdd.png',
    compassNeedleImage: '/dynamic/factions/assets/compass-needle-tdd.png',
    mapIconImages: {
      [MapDataType.INVALID]: '/images/MissingAsset.png',
      [MapDataType.CraftingAlchemy]: '/dynamic/factions/assets/map-icon-alchemy-station-tdd.png',
      [MapDataType.CraftingArtifice]: '/dynamic/factions/assets/map-icon-artificing-station-tdd.png',
      [MapDataType.CraftingCooking]: '/dynamic/factions/assets/map-icon-cooking-station-tdd.png',
      [MapDataType.CraftingForge]: '/dynamic/factions/assets/map-icon-forge-station-tdd.png',
      [MapDataType.CraftingJewels]: '/dynamic/factions/assets/map-icon-jewelry-station-tdd.png',
      [MapDataType.CraftingLeatherworking]: '/dynamic/factions/assets/map-icon-leather-station-tdd.png',
      [MapDataType.CraftingSmithy]: '/dynamic/factions/assets/map-icon-blacksmithing-station-tdd.png',
      [MapDataType.CraftingTailoring]: '/dynamic/factions/assets/map-icon-textile-station-tdd.png',
      [MapDataType.CraftingWoodworking]: '/dynamic/factions/assets/map-icon-woodworking-station-tdd.png',
      [MapDataType.KeepBank]: '/dynamic/factions/assets/map-icon-personal-bank-tdd.png',
      [MapDataType.KeepMain]: '/dynamic/factions/assets/map-icon-keep-tdd.png',
      [MapDataType.KeepRoyalVendor]: '/dynamic/factions/assets/map-icon-royal-vendor-tdd.png',
      [MapDataType.KeepTowerArmory]: '/dynamic/factions/assets/map-icon-armory-tdd.png',
      [MapDataType.KeepTowerBarrack]: '/dynamic/factions/assets/map-icon-barrack-tdd.png',
      [MapDataType.KeepTowerChurch]: '/dynamic/factions/assets/map-icon-church-tdd.png',
      [MapDataType.KeepTowerStable]: '/dynamic/factions/assets/map-icon-stable-tdd.png',
      [MapDataType.Player]: '/dynamic/factions/assets/map-icon-party-member-tdd.png',
      [MapDataType.PortalLocal]: '/dynamic/factions/assets/map-icon-portal-local-tdd.png',
      [MapDataType.PortalZone]: '/dynamic/factions/assets/map-icon-portal-zone-tdd.png',
      [MapDataType.ResourceEssence]: '/dynamic/factions/assets/map-icon-essence-tdd.png',
      [MapDataType.ResourceFishing]: '/dynamic/factions/assets/map-icon-fishing-tdd.png',
      [MapDataType.ResourceHerbs]: '/dynamic/factions/assets/map-icon-herbs-tdd.png',
      [MapDataType.ResourceHunting]: '/dynamic/factions/assets/map-icon-hunting-tdd.png',
      [MapDataType.ResourceLogging]: '/dynamic/factions/assets/map-icon-logging-tdd.png',
      [MapDataType.ResourceMinerals]: '/dynamic/factions/assets/map-icon-minerals-tdd.png',
      [MapDataType.ResourceMining]: '/dynamic/factions/assets/map-icon-mining-tdd.png',
      [MapDataType.Self]: '/dynamic/factions/assets/map-icon-player-tdd.png'
    },
    mapPipImage: '/dynamic/factions/assets/map-icon-tier-pip-tdd.png',
    scrollbarImage: '/dynamic/factions/assets/scrollbar-tdd.png',
    scrollbarShortImage: '/dynamic/factions/assets/scrollbar-short-tdd.png',
    miniMapImage: '/dynamic/factions/assets/mini-map-tdd.png',
    cornerPrimaryTopLeftImage: '/dynamic/factions/assets/corner-primary-tl-tdd.png',
    cornerPrimaryTopRightImage: '/dynamic/factions/assets/corner-primary-tr-tdd.png',
    cornerPrimaryBottomLeftImage: '/dynamic/factions/assets/corner-primary-bl-tdd.png',
    cornerPrimaryBottomRightImage: '/dynamic/factions/assets/corner-primary-br-tdd.png',
    cornerSecondaryTopLeftImage: '/dynamic/factions/assets/corner-secondary-tl-tdd.png',
    cornerSecondaryTopRightImage: '/dynamic/factions/assets/corner-secondary-tr-tdd.png',
    cornerSecondaryBottomLeftImage: '/dynamic/factions/assets/corner-secondary-bl-tdd.png',
    cornerSecondaryBottomRightImage: '/dynamic/factions/assets/corner-secondary-br-tdd.png',
    cornerDecorativeTopLeftImage: '/dynamic/factions/assets/corner-decorative-tl-tdd.png',
    cornerDecorativeTopRightImage: '/dynamic/factions/assets/corner-decorative-tr-tdd.png',
    cornerDecorativeTopRightEmptyImage: '/dynamic/factions/assets/corner-decorative-tr-empty-tdd.png',
    cornerDecorativeBottomLeftImage: '/dynamic/factions/assets/corner-decorative-bl-tdd.png',
    cornerDecorativeBottomRightImage: '/dynamic/factions/assets/corner-decorative-br-tdd.png',
    cornerFancyTopLeftImage: '/dynamic/factions/assets/corner-fancy-tl-tdd.png',
    cornerFancyTopLeftHeaderImage: '/dynamic/factions/assets/corner-fancy-tl-header-tdd.png',
    cornerFancyTopRightImage: '/dynamic/factions/assets/corner-fancy-tr-tdd.png',
    cornerFancyTopRightHeaderImage: '/dynamic/factions/assets/corner-fancy-tr-header-tdd.png',
    cornerFancyBottomLeftImage: '/dynamic/factions/assets/corner-fancy-bl-tdd.png',
    cornerFancyBottomRightImage: '/dynamic/factions/assets/corner-fancy-br-tdd.png',
    edgeDecorativeTopImage: '/dynamic/factions/assets/edge-decorative-top-tdd.png',
    edgeDecorativeLeftImage: '/dynamic/factions/assets/edge-decorative-left-tdd.png',
    edgeDecorativeRightImage: '/dynamic/factions/assets/edge-decorative-right-tdd.png',
    edgeDecorativeBottomImage: '/dynamic/factions/assets/edge-decorative-bottom-tdd.png',
    edgeFancyTopImage: '/dynamic/factions/assets/edge-fancy-top-tdd.png',
    headerFancyBookendImage: '/dynamic/factions/assets/header-fancy-bookend-tdd.png',
    borderColor: '#b58954',
    targetBorderColor: '#03c900',
    squareBackgroundImage: '/dynamic/factions/assets/square-background-tdd.png',
    bagBackgroundImage: '/dynamic/factions/assets/bag-background-tdd.png',
    searchBackgroundColor: '#251f1c',
    hudnavIconGameMenuImage: '/dynamic/factions/assets/hudnav-icon-settings-tdd.png',
    hudnavIconWorldMapImage: '/dynamic/factions/assets/hudnav-icon-map-tdd.png',
    hudnavIconEquippedImage: '/dynamic/factions/assets/hudnav-icon-equipped-tdd.png',
    hudnavIconInventoryImage: '/dynamic/factions/assets/hudnav-icon-inventory-tdd.png',
    hudnavIconGameInfoImage: '/dynamic/factions/assets/hudnav-icon-gameinfo-tdd.png',
    hudnavIconAbilityBookImage: '/dynamic/factions/assets/hudnav-icon-abilitybook-tdd.png',
    hudnavIconMailImage: '/dynamic/factions/assets/hudnav-icon-mail-tdd.png',
    hudnavIconGuildImage: '/dynamic/factions/assets/hudnav-icon-guild-tdd.png',
    hudnavIconQuestLogImage: '/dynamic/factions/assets/hudnav-icon-questlog-tdd.png',
    hudnavEndImage: '/dynamic/factions/assets/hudnav-end-tdd.png',
    sendButtonImage: '/dynamic/factions/assets/send-button-tdd.png',
    gearSlotImages: [
      { gearSlotID: 'Head', image: '/dynamic/factions/assets/gear-slot-helm-tdd.png' },
      { gearSlotID: 'Back', image: '/dynamic/factions/assets/gear-slot-cloak-tdd.png' },
      { gearSlotID: 'Torso', image: '/dynamic/factions/assets/gear-slot-chest-tdd.png' },
      { gearSlotID: 'Arms', image: '/dynamic/factions/assets/gear-slot-elbows-tdd.png' },
      { gearSlotID: 'Hands', image: '/dynamic/factions/assets/gear-slot-hands-tdd.png' },
      { gearSlotID: 'Legs', image: '/dynamic/factions/assets/gear-slot-pants-tdd.png' },
      { gearSlotID: 'Feet', image: '/dynamic/factions/assets/gear-slot-boots-tdd.png' },
      { gearSlotID: 'Earring1', image: '/dynamic/factions/assets/gear-slot-rings-tdd.png' },
      { gearSlotID: 'Earring2', image: '/dynamic/factions/assets/gear-slot-rings-tdd.png' },
      { gearSlotID: 'Neck', image: '/dynamic/factions/assets/gear-slot-necklace-tdd.png' },
      { gearSlotID: 'Ring1', image: '/dynamic/factions/assets/gear-slot-rings-tdd.png' },
      { gearSlotID: 'Ring2', image: '/dynamic/factions/assets/gear-slot-rings-tdd.png' },
      { gearSlotID: 'OneHandedWeaponLeft', image: '/dynamic/factions/assets/gear-slot-off-hand-tdd.png' },
      { gearSlotID: 'OneHandedWeaponRight', image: '/dynamic/factions/assets/gear-slot-main-hand-tdd.png' }
    ],
    prospectingBackgroundImage: '/dynamic/factions/assets/prospecting-background-tdd.png',
    universalUnitFrameForegroundImage: '/dynamic/factions/assets/unit-frame-front-universal-tdd.png',
    universalUnitFrameBackgroundImage: '/dynamic/factions/assets/unit-frame-back-universal-tdd.png',
    arrowLeftImage: '/dynamic/factions/assets/arrow-left-tdd.png',
    arrowPointerImage: '/dynamic/factions/assets/arrow-pointer-tdd.png',
    buttonBackgroundImage: '/dynamic/factions/assets/button-background-tdd.png',
    buttonBackgroundMediumImage: '/dynamic/factions/assets/button-background-med-tdd.png',
    buttonBackgroundSmallImage: '/dynamic/factions/assets/button-background-small-tdd.png',
    buttonSquareBackgroundImage: '/dynamic/factions/assets/button-square-tdd.png',
    checkboxBackgroundImage: '/dynamic/factions/assets/checkbox-background-tdd.png',
    sliderMiniImage: '/dynamic/factions/assets/slider-mini-tdd.png',
    goldBackgroundImage: '/dynamic/factions/assets/gold-background-tdd.png',
    dividerVerticalImage: '/dynamic/factions/assets/divider-vertical-tdd.png',
    dividerVerticalHalfImage: '/dynamic/factions/assets/divider-vertical-half-tdd.png',
    dividerVerticalSimpleImage: '/dynamic/factions/assets/divider-vertical-tdd-simple.png',
    mailDividerColor: '#b58954',
    mailSenderColor: '#00c900',
    mailMessageBackgroundImage: '/dynamic/factions/assets/mail-message-background-tdd.png',
    mailRowBackgroundImage: '/dynamic/factions/assets/mail-row-background-tdd.png',
    mailRowPaperImage: '/dynamic/factions/assets/mail-row-paper-tdd.png',
    selectionGlowColor: '#03c900',
    warbandPartyBackgroundImage: '/dynamic/factions/assets/warband-party-bg-tdd.png',
    iconArmorSaleImage: '/dynamic/factions/assets/icon-armor-sale-tdd.png',
    iconArmorSaleLargeImage: '/dynamic/factions/assets/icon-armor-sale-large-tdd.png',
    iconCastleImage: '/dynamic/factions/assets/icon-castle-tdd.png',
    iconCastleLargeImage: '/dynamic/factions/assets/icon-castle-large-tdd.png',
    iconCrownImage: '/dynamic/factions/assets/icon-crown-tdd.png',
    iconCrownLargeImage: '/dynamic/factions/assets/icon-crown-large-tdd.png',
    iconTutorialImage: '/dynamic/factions/assets/icon-tutorial-tdd.png',
    iconMiscSaleImage: '/dynamic/factions/assets/icon-misc-sale-tdd.png',
    iconMiscSaleLargeImage: '/dynamic/factions/assets/icon-misc-sale-large-tdd.png',
    iconWeaponSaleImage: '/dynamic/factions/assets/icon-weapon-sale-tdd.png',
    iconWeaponSaleLargeImage: '/dynamic/factions/assets/icon-weapon-sale-large-tdd.png',
    headerBorderImage: '/dynamic/factions/assets/header-border-tdd.png',
    headerBorderSecondaryImage: '/dynamic/factions/assets/header-border-secondary-tdd.png',
    endcapImage: '/dynamic/factions/assets/endcap-tdd.png',
    factionShieldImage: '/dynamic/factions/assets/faction-shield-tdd.png',
    backgroundRealmVideo: '/dynamic/factions/assets/background-realm-tdd.webm',
    progressBarImage: '/dynamic/factions/assets/progress-bar-fill-tdd.png',
    progressBarCircleFillImage: '/dynamic/factions/assets/progress-bar-fill-circle-tdd.png',
    progressBarCircleBackgroundImage: '/dynamic/factions/assets/progress-bar-background-circle-tdd.png',
    flagBlankImage: '/dynamic/factions/assets/flag-blank-tdd.png',
    taperBarImage: '/dynamic/factions/assets/taper-bar-tdd.png',
    mapGlobeImage: '/dynamic/factions/assets/map-icon-globe-tdd.png'
  },
  {
    id: 'Viking',
    backgroundBookImage: '/dynamic/factions/assets/ability-book-background-viking.png',
    backgroundCharacterImage: '/dynamic/factions/assets/background-character-viking.png',
    backgroundClassIconImage: '/dynamic/factions/assets/ability-book-class-icon-background-viking.png',
    backgroundFullscreenImage: 'dynamic/factions/assets/background-fullscreen-viking.png',
    backgroundLeatherImage: '/dynamic/factions/assets/background-leather-viking.png',
    backgroundProgressBarImage: '/dynamic/factions/assets/background-progress-bar-viking.png',
    nameplateIconFrameImage: '/dynamic/factions/assets/vik-default-frame.png',
    abilityBarEmptySlotImage: '/dynamic/factions/assets/vik-empty-slot.png',
    nameplateBackgroundImage: '/dynamic/factions/assets/vik-nameplate-bg.png',
    nameplateMainFrameImage: '/dynamic/factions/assets/vik-main-frame.png',
    nameplateMiniFrameImage: '/dynamic/factions/assets/vik-mini-frame.png',
    nameplateProfileImage: '/dynamic/factions/assets/vik-propic.png',
    paperdollBackgroundImage: '/dynamic/factions/assets/bg-vik.png',
    paperdollBaseImage: '/dynamic/factions/assets/vik-base.png',
    factionSelectBackgroundImage: '/dynamic/factions/assets/faction-select-bg-vik.jpg',
    factionSelectEmblemImage: '/dynamic/factions/assets/faction-select-emblem-vik.png',
    unitFrameBackgroundImage: '/dynamic/factions/assets/unit-frame-back-viking.png',
    unitFrameForegroundImage: '/dynamic/factions/assets/unit-frame-front-viking.png',
    unitFrameForegroundTargetImage: '/dynamic/factions/assets/unit-frame-front-target-viking.png',
    unitFrameForegroundPartyMemberImage: '/dynamic/factions/assets/unit-frame-front-party-member-viking.png',
    unitFrameForegroundPartyLeaderImage: '/dynamic/factions/assets/unit-frame-front-party-leader-viking.png',
    unitFrameJudgementPipBackground: '/dynamic/factions/assets/unit-frame-judgement-pip-viking.png',
    unitFrameResourceDividerImage: '/dynamic/factions/assets/unit-frame-resource-divider-viking.png',
    unitFrameDeterminationPipBorder: '/dynamic/factions/assets/unit-frame-determination-pip-viking.png',
    simpleUnitFrameBackgroundImage: '/dynamic/factions/assets/unit-frame-back-simple-viking.png',
    simpleUnitFrameForegroundImage: '/dynamic/factions/assets/unit-frame-front-simple-viking.png',
    simpleUnitFrameForegroundRightImage: '/dynamic/factions/assets/unit-frame-front-simple-right-viking.png',
    simpleUnitFrameForegroundPartyMemberImage: '/dynamic/factions/assets/unit-frame-front-simple-viking.png',
    simpleUnitFrameForegroundPartyLeaderImage: '/dynamic/factions/assets/unit-frame-front-simple-viking.png',
    abilityBarLeftImage: '/dynamic/factions/assets/ability-bar-left-viking.png',
    abilityBarLeftBlankImage: '/dynamic/factions/assets/ability-bar-left-blank-viking.png',
    abilityBarRightImage: '/dynamic/factions/assets/ability-bar-right-viking.png',
    abilityBarRightBlankImage: '/dynamic/factions/assets/ability-bar-right-blank-viking.png',
    abilityBarCenterFrontImage: '/dynamic/factions/assets/ability-bar-center-front-viking.png',
    abilityBarCenterBackImage: '/dynamic/factions/assets/ability-bar-center-back-viking.png',
    abilityBarCenterDecorTopImage: '/dynamic/factions/assets/ability-bar-center-decor-top-viking.png',
    abilityBarCenterDecorBottomImage: '/dynamic/factions/assets/ability-bar-center-decor-bottom-viking.png',
    borderImage: '/dynamic/factions/assets/border-viking.png',
    borderCloseWindowImage: '/dynamic/factions/assets/border-close-window-viking.png',
    windowBackgroundImage: '/dynamic/factions/assets/window-background-viking.jpg',
    windowCloseImage: '/dynamic/factions/assets/window-close-viking.png',
    windowLockImage: '/dynamic/factions/assets/window-lock-viking.png',
    windowMaximizeImage: '/dynamic/factions/assets/window-maximize-viking.png',
    windowUnlockImage: '/dynamic/factions/assets/window-unlock-viking.png',
    windowWindowedImage: '/dynamic/factions/assets/window-windowed-viking.png',
    compassNeedleImage: '/dynamic/factions/assets/compass-needle-viking.png',
    mapIconImages: {
      [MapDataType.INVALID]: '/images/MissingAsset.png',
      [MapDataType.CraftingAlchemy]: '/dynamic/factions/assets/map-icon-alchemy-station-viking.png',
      [MapDataType.CraftingArtifice]: '/dynamic/factions/assets/map-icon-artificing-station-viking.png',
      [MapDataType.CraftingCooking]: '/dynamic/factions/assets/map-icon-cooking-station-viking.png',
      [MapDataType.CraftingForge]: '/dynamic/factions/assets/map-icon-forge-station-viking.png',
      [MapDataType.CraftingJewels]: '/dynamic/factions/assets/map-icon-jewelry-station-viking.png',
      [MapDataType.CraftingLeatherworking]: '/dynamic/factions/assets/map-icon-leather-station-viking.png',
      [MapDataType.CraftingSmithy]: '/dynamic/factions/assets/map-icon-blacksmithing-station-viking.png',
      [MapDataType.CraftingTailoring]: '/dynamic/factions/assets/map-icon-textile-station-viking.png',
      [MapDataType.CraftingWoodworking]: '/dynamic/factions/assets/map-icon-woodworking-station-viking.png',
      [MapDataType.KeepBank]: '/dynamic/factions/assets/map-icon-personal-bank-viking.png',
      [MapDataType.KeepMain]: '/dynamic/factions/assets/map-icon-keep-viking.png',
      [MapDataType.KeepRoyalVendor]: '/dynamic/factions/assets/map-icon-royal-vendor-viking.png',
      [MapDataType.KeepTowerArmory]: '/dynamic/factions/assets/map-icon-armory-viking.png',
      [MapDataType.KeepTowerBarrack]: '/dynamic/factions/assets/map-icon-barrack-viking.png',
      [MapDataType.KeepTowerChurch]: '/dynamic/factions/assets/map-icon-church-viking.png',
      [MapDataType.KeepTowerStable]: '/dynamic/factions/assets/map-icon-stable-viking.png',
      [MapDataType.Player]: '/dynamic/factions/assets/map-icon-party-member-viking.png',
      [MapDataType.PortalLocal]: '/dynamic/factions/assets/map-icon-portal-local-viking.png',
      [MapDataType.PortalZone]: '/dynamic/factions/assets/map-icon-portal-zone-viking.png',
      [MapDataType.ResourceEssence]: '/dynamic/factions/assets/map-icon-essence-viking.png',
      [MapDataType.ResourceFishing]: '/dynamic/factions/assets/map-icon-fishing-viking.png',
      [MapDataType.ResourceHerbs]: '/dynamic/factions/assets/map-icon-herbs-viking.png',
      [MapDataType.ResourceHunting]: '/dynamic/factions/assets/map-icon-hunting-viking.png',
      [MapDataType.ResourceLogging]: '/dynamic/factions/assets/map-icon-logging-viking.png',
      [MapDataType.ResourceMinerals]: '/dynamic/factions/assets/map-icon-minerals-viking.png',
      [MapDataType.ResourceMining]: '/dynamic/factions/assets/map-icon-mining-viking.png',
      [MapDataType.Self]: '/dynamic/factions/assets/map-icon-player-viking.png'
    },
    mapPipImage: '/dynamic/factions/assets/map-icon-tier-pip-viking.png',
    scrollbarImage: '/dynamic/factions/assets/scrollbar-viking.png',
    scrollbarShortImage: '/dynamic/factions/assets/scrollbar-short-viking.png',
    miniMapImage: '/dynamic/factions/assets/mini-map-viking.png',
    cornerPrimaryTopLeftImage: '/dynamic/factions/assets/corner-primary-tl-viking.png',
    cornerPrimaryTopRightImage: '/dynamic/factions/assets/corner-primary-tr-viking.png',
    cornerPrimaryBottomLeftImage: '/dynamic/factions/assets/corner-primary-bl-viking.png',
    cornerPrimaryBottomRightImage: '/dynamic/factions/assets/corner-primary-br-viking.png',
    cornerSecondaryTopLeftImage: '/dynamic/factions/assets/corner-secondary-tl-viking.png',
    cornerSecondaryTopRightImage: '/dynamic/factions/assets/corner-secondary-tr-viking.png',
    cornerSecondaryBottomLeftImage: '/dynamic/factions/assets/corner-secondary-bl-viking.png',
    cornerSecondaryBottomRightImage: '/dynamic/factions/assets/corner-secondary-br-viking.png',
    cornerDecorativeTopLeftImage: '/dynamic/factions/assets/corner-decorative-tl-viking.png',
    cornerDecorativeTopRightImage: '/dynamic/factions/assets/corner-decorative-tr-viking.png',
    cornerDecorativeTopRightEmptyImage: '/dynamic/factions/assets/corner-decorative-tr-empty-viking.png',
    cornerDecorativeBottomLeftImage: '/dynamic/factions/assets/corner-decorative-bl-viking.png',
    cornerDecorativeBottomRightImage: '/dynamic/factions/assets/corner-decorative-br-viking.png',
    cornerFancyTopLeftImage: '/dynamic/factions/assets/corner-fancy-tl-viking.png',
    cornerFancyTopLeftHeaderImage: '/dynamic/factions/assets/corner-fancy-tl-header-viking.png',
    cornerFancyTopRightImage: '/dynamic/factions/assets/corner-fancy-tr-viking.png',
    cornerFancyTopRightHeaderImage: '/dynamic/factions/assets/corner-fancy-tr-header-viking.png',
    cornerFancyBottomLeftImage: '/dynamic/factions/assets/corner-fancy-bl-viking.png',
    cornerFancyBottomRightImage: '/dynamic/factions/assets/corner-fancy-br-viking.png',
    edgeDecorativeTopImage: '/dynamic/factions/assets/edge-decorative-top-viking.png',
    edgeDecorativeLeftImage: '/dynamic/factions/assets/edge-decorative-left-viking.png',
    edgeDecorativeRightImage: '/dynamic/factions/assets/edge-decorative-right-viking.png',
    edgeDecorativeBottomImage: '/dynamic/factions/assets/edge-decorative-bottom-viking.png',
    edgeFancyTopImage: '/dynamic/factions/assets/edge-fancy-top-viking.png',
    headerFancyBookendImage: '/dynamic/factions/assets/header-fancy-bookend-viking.png',
    borderColor: '#ddeffe',
    targetBorderColor: '#00baff',
    squareBackgroundImage: '/dynamic/factions/assets/square-background-viking.png',
    bagBackgroundImage: '/dynamic/factions/assets/bag-background-viking.png',
    searchBackgroundColor: '#1b1c20',
    hudnavIconGameMenuImage: '/dynamic/factions/assets/hudnav-icon-settings-viking.png',
    hudnavIconWorldMapImage: '/dynamic/factions/assets/hudnav-icon-map-viking.png',
    hudnavIconEquippedImage: '/dynamic/factions/assets/hudnav-icon-equipped-viking.png',
    hudnavIconInventoryImage: '/dynamic/factions/assets/hudnav-icon-inventory-viking.png',
    hudnavIconGameInfoImage: '/dynamic/factions/assets/hudnav-icon-gameinfo-viking.png',
    hudnavIconAbilityBookImage: '/dynamic/factions/assets/hudnav-icon-abilitybook-viking.png',
    hudnavIconMailImage: '/dynamic/factions/assets/hudnav-icon-mail-viking.png',
    hudnavIconGuildImage: '/dynamic/factions/assets/hudnav-icon-guild-viking.png',
    hudnavIconQuestLogImage: '/dynamic/factions/assets/hudnav-icon-questlog-viking.png',
    hudnavEndImage: '/dynamic/factions/assets/hudnav-end-viking.png',
    sendButtonImage: '/dynamic/factions/assets/send-button-viking.png',
    gearSlotImages: [
      { gearSlotID: 'Head', image: '/dynamic/factions/assets/gear-slot-helm-viking.png' },
      { gearSlotID: 'Back', image: '/dynamic/factions/assets/gear-slot-cloak-viking.png' },
      { gearSlotID: 'Torso', image: '/dynamic/factions/assets/gear-slot-chest-viking.png' },
      { gearSlotID: 'Arms', image: '/dynamic/factions/assets/gear-slot-elbows-viking.png' },
      { gearSlotID: 'Hands', image: '/dynamic/factions/assets/gear-slot-hands-viking.png' },
      { gearSlotID: 'Legs', image: '/dynamic/factions/assets/gear-slot-pants-viking.png' },
      { gearSlotID: 'Feet', image: '/dynamic/factions/assets/gear-slot-boots-viking.png' },
      { gearSlotID: 'Earring1', image: '/dynamic/factions/assets/gear-slot-rings-viking.png' },
      { gearSlotID: 'Earring2', image: '/dynamic/factions/assets/gear-slot-rings-viking.png' },
      { gearSlotID: 'Neck', image: '/dynamic/factions/assets/gear-slot-necklace-viking.png' },
      { gearSlotID: 'Ring1', image: '/dynamic/factions/assets/gear-slot-rings-viking.png' },
      { gearSlotID: 'Ring2', image: '/dynamic/factions/assets/gear-slot-rings-viking.png' },
      { gearSlotID: 'OneHandedWeaponLeft', image: '/dynamic/factions/assets/gear-slot-off-hand-viking.png' },
      { gearSlotID: 'OneHandedWeaponRight', image: '/dynamic/factions/assets/gear-slot-main-hand-viking.png' }
    ],
    prospectingBackgroundImage: '/dynamic/factions/assets/prospecting-background-viking.png',
    universalUnitFrameForegroundImage: '/dynamic/factions/assets/unit-frame-front-universal-viking.png',
    universalUnitFrameBackgroundImage: '/dynamic/factions/assets/unit-frame-back-universal-viking.png',
    arrowLeftImage: '/dynamic/factions/assets/arrow-left-viking.png',
    arrowPointerImage: '/dynamic/factions/assets/arrow-pointer-viking.png',
    buttonBackgroundImage: '/dynamic/factions/assets/button-background-viking.png',
    buttonBackgroundMediumImage: '/dynamic/factions/assets/button-background-med-viking.png',
    buttonBackgroundSmallImage: '/dynamic/factions/assets/button-background-small-viking.png',
    buttonSquareBackgroundImage: '/dynamic/factions/assets/button-square-viking.png',
    checkboxBackgroundImage: '/dynamic/factions/assets/checkbox-background-viking.png',
    sliderMiniImage: '/dynamic/factions/assets/slider-mini-viking.png',
    goldBackgroundImage: '/dynamic/factions/assets/gold-background-viking.png',
    dividerVerticalImage: '/dynamic/factions/assets/divider-vertical-viking.png',
    dividerVerticalHalfImage: '/dynamic/factions/assets/divider-vertical-half-viking.png',
    dividerVerticalSimpleImage: '/dynamic/factions/assets/divider-vertical-viking-simple.png',
    mailDividerColor: '#ddeffe',
    mailSenderColor: '#a6d7ff',
    mailMessageBackgroundImage: '/dynamic/factions/assets/mail-message-background-viking.png',
    mailRowBackgroundImage: '/dynamic/factions/assets/mail-row-background-viking.png',
    mailRowPaperImage: '/dynamic/factions/assets/mail-row-paper-viking.png',
    selectionGlowColor: '#00baff',
    warbandPartyBackgroundImage: '/dynamic/factions/assets/warband-party-bg-viking.png',
    iconArmorSaleImage: '/dynamic/factions/assets/icon-armor-sale-viking.png',
    iconArmorSaleLargeImage: '/dynamic/factions/assets/icon-armor-sale-large-viking.png',
    iconCastleImage: '/dynamic/factions/assets/icon-castle-viking.png',
    iconCastleLargeImage: '/dynamic/factions/assets/icon-castle-large-viking.png',
    iconCrownImage: '/dynamic/factions/assets/icon-crown-viking.png',
    iconCrownLargeImage: '/dynamic/factions/assets/icon-crown-large-viking.png',
    iconTutorialImage: '/dynamic/factions/assets/icon-tutorial-viking.png',
    iconMiscSaleImage: '/dynamic/factions/assets/icon-misc-sale-viking.png',
    iconMiscSaleLargeImage: '/dynamic/factions/assets/icon-misc-sale-large-viking.png',
    iconWeaponSaleImage: '/dynamic/factions/assets/icon-weapon-sale-viking.png',
    iconWeaponSaleLargeImage: '/dynamic/factions/assets/icon-weapon-sale-large-viking.png',
    headerBorderImage: '/dynamic/factions/assets/header-border-viking.png',
    headerBorderSecondaryImage: '/dynamic/factions/assets/header-border-secondary-viking.png',
    endcapImage: '/dynamic/factions/assets/endcap-viking.png',
    factionShieldImage: '/dynamic/factions/assets/faction-shield-viking.png',
    backgroundRealmVideo: '/dynamic/factions/assets/background-realm-viking.webm',
    progressBarImage: '/dynamic/factions/assets/progress-bar-fill-viking.png',
    progressBarCircleFillImage: '/dynamic/factions/assets/progress-bar-fill-circle-viking.png',
    progressBarCircleBackgroundImage: '/dynamic/factions/assets/progress-bar-background-circle-viking.png',
    flagBlankImage: '/dynamic/factions/assets/flag-blank-viking.png',
    taperBarImage: '/dynamic/factions/assets/taper-bar-viking.png',
    mapGlobeImage: '/dynamic/factions/assets/map-icon-globe-viking.png'
  },
  {
    id: 'Arthurian',
    backgroundBookImage: '/dynamic/factions/assets/ability-book-background-arthurian.png',
    backgroundCharacterImage: '/dynamic/factions/assets/background-character-arthurian.png',
    backgroundClassIconImage: '/dynamic/factions/assets/ability-book-class-icon-background-arthurian.png',
    backgroundFullscreenImage: 'dynamic/factions/assets/background-fullscreen-arthurian.png',
    backgroundLeatherImage: '/dynamic/factions/assets/background-leather-arthurian.png',
    backgroundProgressBarImage: '/dynamic/factions/assets/background-progress-bar-arthurian.png',
    nameplateIconFrameImage: '/dynamic/factions/assets/art-default-frame.png',
    abilityBarEmptySlotImage: '/dynamic/factions/assets/art-empty-slot.png',
    nameplateBackgroundImage: '/dynamic/factions/assets/art-nameplate-bg.png',
    nameplateMainFrameImage: '/dynamic/factions/assets/art-main-frame.png',
    nameplateMiniFrameImage: '/dynamic/factions/assets/art-mini-frame.png',
    nameplateProfileImage: '/dynamic/factions/assets/art-propic.png',
    paperdollBackgroundImage: '/dynamic/factions/assets/bg-art.png',
    paperdollBaseImage: '/dynamic/factions/assets/art-base.png',
    factionSelectBackgroundImage: '/dynamic/factions/assets/faction-select-bg-art.jpg',
    factionSelectEmblemImage: '/dynamic/factions/assets/faction-select-emblem-art.png',
    unitFrameBackgroundImage: '/dynamic/factions/assets/unit-frame-back-arthurian.png',
    unitFrameForegroundImage: '/dynamic/factions/assets/unit-frame-front-arthurian.png',
    unitFrameForegroundTargetImage: '/dynamic/factions/assets/unit-frame-front-target-arthurian.png',
    unitFrameForegroundPartyMemberImage: '/dynamic/factions/assets/unit-frame-front-party-member-arthurian.png',
    unitFrameForegroundPartyLeaderImage: '/dynamic/factions/assets/unit-frame-front-party-leader-arthurian.png',
    unitFrameJudgementPipBackground: '/dynamic/factions/assets/unit-frame-judgement-pip-arthurian.png',
    unitFrameResourceDividerImage: '/dynamic/factions/assets/unit-frame-resource-divider-arthurian.png',
    unitFrameDeterminationPipBorder: '/dynamic/factions/assets/unit-frame-determination-pip-arthurian.png',
    simpleUnitFrameBackgroundImage: '/dynamic/factions/assets/unit-frame-back-simple-arthurian.png',
    simpleUnitFrameForegroundImage: '/dynamic/factions/assets/unit-frame-front-simple-arthurian.png',
    simpleUnitFrameForegroundRightImage: '/dynamic/factions/assets/unit-frame-front-simple-right-arthurian.png',
    simpleUnitFrameForegroundPartyMemberImage: '/dynamic/factions/assets/unit-frame-front-simple-arthurian.png',
    simpleUnitFrameForegroundPartyLeaderImage: '/dynamic/factions/assets/unit-frame-front-simple-arthurian.png',
    abilityBarLeftImage: '/dynamic/factions/assets/ability-bar-left-arthurian.png',
    abilityBarLeftBlankImage: '/dynamic/factions/assets/ability-bar-left-blank-arthurian.png',
    abilityBarRightImage: '/dynamic/factions/assets/ability-bar-right-arthurian.png',
    abilityBarRightBlankImage: '/dynamic/factions/assets/ability-bar-right-blank-arthurian.png',
    abilityBarCenterFrontImage: '/dynamic/factions/assets/ability-bar-center-front-arthurian.png',
    abilityBarCenterBackImage: '/dynamic/factions/assets/ability-bar-center-back-arthurian.png',
    abilityBarCenterDecorTopImage: '/dynamic/factions/assets/ability-bar-center-decor-top-arthurian.png',
    abilityBarCenterDecorBottomImage: '/dynamic/factions/assets/ability-bar-center-decor-bottom-arthurian.png',
    borderImage: '/dynamic/factions/assets/border-arthurian.png',
    borderCloseWindowImage: '/dynamic/factions/assets/border-close-window-arthurian.png',
    windowBackgroundImage: '/dynamic/factions/assets/window-background-arthurian.jpg',
    windowCloseImage: '/dynamic/factions/assets/window-close-arthurian.png',
    windowLockImage: '/dynamic/factions/assets/window-lock-arthurian.png',
    windowMaximizeImage: '/dynamic/factions/assets/window-maximize-arthurian.png',
    windowUnlockImage: '/dynamic/factions/assets/window-unlock-arthurian.png',
    windowWindowedImage: '/dynamic/factions/assets/window-windowed-arthurian.png',
    compassNeedleImage: '/dynamic/factions/assets/compass-needle-arthurian.png',
    mapIconImages: {
      [MapDataType.INVALID]: '/images/MissingAsset.png',
      [MapDataType.CraftingAlchemy]: '/dynamic/factions/assets/map-icon-alchemy-station-arthurian.png',
      [MapDataType.CraftingArtifice]: '/dynamic/factions/assets/map-icon-artificing-station-arthurian.png',
      [MapDataType.CraftingCooking]: '/dynamic/factions/assets/map-icon-cooking-station-arthurian.png',
      [MapDataType.CraftingForge]: '/dynamic/factions/assets/map-icon-forge-station-arthurian.png',
      [MapDataType.CraftingJewels]: '/dynamic/factions/assets/map-icon-jewelry-station-arthurian.png',
      [MapDataType.CraftingLeatherworking]: '/dynamic/factions/assets/map-icon-leather-station-arthurian.png',
      [MapDataType.CraftingSmithy]: '/dynamic/factions/assets/map-icon-blacksmithing-station-arthurian.png',
      [MapDataType.CraftingTailoring]: '/dynamic/factions/assets/map-icon-textile-station-arthurian.png',
      [MapDataType.CraftingWoodworking]: '/dynamic/factions/assets/map-icon-woodworking-station-arthurian.png',
      [MapDataType.KeepBank]: '/dynamic/factions/assets/map-icon-personal-bank-arthurian.png',
      [MapDataType.KeepMain]: '/dynamic/factions/assets/map-icon-keep-arthurian.png',
      [MapDataType.KeepRoyalVendor]: '/dynamic/factions/assets/map-icon-royal-vendor-arthurian.png',
      [MapDataType.KeepTowerArmory]: '/dynamic/factions/assets/map-icon-armory-arthurian.png',
      [MapDataType.KeepTowerBarrack]: '/dynamic/factions/assets/map-icon-barrack-arthurian.png',
      [MapDataType.KeepTowerChurch]: '/dynamic/factions/assets/map-icon-church-arthurian.png',
      [MapDataType.KeepTowerStable]: '/dynamic/factions/assets/map-icon-stable-arthurian.png',
      [MapDataType.Player]: '/dynamic/factions/assets/map-icon-party-member-arthurian.png',
      [MapDataType.PortalLocal]: '/dynamic/factions/assets/map-icon-portal-local-arthurian.png',
      [MapDataType.PortalZone]: '/dynamic/factions/assets/map-icon-portal-zone-arthurian.png',
      [MapDataType.ResourceEssence]: '/dynamic/factions/assets/map-icon-essence-arthurian.png',
      [MapDataType.ResourceFishing]: '/dynamic/factions/assets/map-icon-fishing-arthurian.png',
      [MapDataType.ResourceHerbs]: '/dynamic/factions/assets/map-icon-herbs-arthurian.png',
      [MapDataType.ResourceHunting]: '/dynamic/factions/assets/map-icon-hunting-arthurian.png',
      [MapDataType.ResourceLogging]: '/dynamic/factions/assets/map-icon-logging-arthurian.png',
      [MapDataType.ResourceMinerals]: '/dynamic/factions/assets/map-icon-minerals-arthurian.png',
      [MapDataType.ResourceMining]: '/dynamic/factions/assets/map-icon-mining-arthurian.png',
      [MapDataType.Self]: '/dynamic/factions/assets/map-icon-player-arthurian.png'
    },
    mapPipImage: '/dynamic/factions/assets/map-icon-tier-pip-arthurian.png',
    scrollbarImage: '/dynamic/factions/assets/scrollbar-arthurian.png',
    scrollbarShortImage: '/dynamic/factions/assets/scrollbar-short-arthurian.png',
    miniMapImage: '/dynamic/factions/assets/mini-map-arthurian.png',
    cornerPrimaryTopLeftImage: '/dynamic/factions/assets/corner-primary-tl-arthurian.png',
    cornerPrimaryTopRightImage: '/dynamic/factions/assets/corner-primary-tr-arthurian.png',
    cornerPrimaryBottomLeftImage: '/dynamic/factions/assets/corner-primary-bl-arthurian.png',
    cornerPrimaryBottomRightImage: '/dynamic/factions/assets/corner-primary-br-arthurian.png',
    cornerSecondaryTopLeftImage: '/dynamic/factions/assets/corner-secondary-tl-arthurian.png',
    cornerSecondaryTopRightImage: '/dynamic/factions/assets/corner-secondary-tr-arthurian.png',
    cornerSecondaryBottomLeftImage: '/dynamic/factions/assets/corner-secondary-bl-arthurian.png',
    cornerSecondaryBottomRightImage: '/dynamic/factions/assets/corner-secondary-br-arthurian.png',
    cornerDecorativeTopLeftImage: '/dynamic/factions/assets/corner-decorative-tl-arthurian.png',
    cornerDecorativeTopRightImage: '/dynamic/factions/assets/corner-decorative-tr-arthurian.png',
    cornerDecorativeTopRightEmptyImage: '/dynamic/factions/assets/corner-decorative-tr-empty-arthurian.png',
    cornerDecorativeBottomLeftImage: '/dynamic/factions/assets/corner-decorative-bl-arthurian.png',
    cornerDecorativeBottomRightImage: '/dynamic/factions/assets/corner-decorative-br-arthurian.png',
    cornerFancyTopLeftImage: '/dynamic/factions/assets/corner-fancy-tl-arthurian.png',
    cornerFancyTopLeftHeaderImage: '/dynamic/factions/assets/corner-fancy-tl-header-arthurian.png',
    cornerFancyTopRightImage: '/dynamic/factions/assets/corner-fancy-tr-arthurian.png',
    cornerFancyTopRightHeaderImage: '/dynamic/factions/assets/corner-fancy-tr-header-arthurian.png',
    cornerFancyBottomLeftImage: '/dynamic/factions/assets/corner-fancy-bl-arthurian.png',
    cornerFancyBottomRightImage: '/dynamic/factions/assets/corner-fancy-br-arthurian.png',
    edgeDecorativeTopImage: '/dynamic/factions/assets/edge-decorative-top-arthurian.png',
    edgeDecorativeLeftImage: '/dynamic/factions/assets/edge-decorative-left-arthurian.png',
    edgeDecorativeRightImage: '/dynamic/factions/assets/edge-decorative-right-arthurian.png',
    edgeDecorativeBottomImage: '/dynamic/factions/assets/edge-decorative-bottom-arthurian.png',
    edgeFancyTopImage: '/dynamic/factions/assets/edge-fancy-top-arthurian.png',
    headerFancyBookendImage: '/dynamic/factions/assets/header-fancy-bookend-arthurian.png',
    borderColor: '#aaa9a9',
    targetBorderColor: '#ffc000',
    squareBackgroundImage: '/dynamic/factions/assets/square-background-arthurian.png',
    bagBackgroundImage: '/dynamic/factions/assets/bag-background-arthurian.png',
    searchBackgroundColor: '#1b1b1b',
    hudnavIconGameMenuImage: '/dynamic/factions/assets/hudnav-icon-settings-arthurian.png',
    hudnavIconWorldMapImage: '/dynamic/factions/assets/hudnav-icon-map-arthurian.png',
    hudnavIconEquippedImage: '/dynamic/factions/assets/hudnav-icon-equipped-arthurian.png',
    hudnavIconInventoryImage: '/dynamic/factions/assets/hudnav-icon-inventory-arthurian.png',
    hudnavIconGameInfoImage: '/dynamic/factions/assets/hudnav-icon-gameinfo-arthurian.png',
    hudnavIconAbilityBookImage: '/dynamic/factions/assets/hudnav-icon-abilitybook-arthurian.png',
    hudnavIconMailImage: '/dynamic/factions/assets/hudnav-icon-mail-arthurian.png',
    hudnavIconGuildImage: '/dynamic/factions/assets/hudnav-icon-guild-arthurian.png',
    hudnavIconQuestLogImage: '/dynamic/factions/assets/hudnav-icon-questlog-arthurian.png',
    hudnavEndImage: '/dynamic/factions/assets/hudnav-end-arthurian.png',
    sendButtonImage: '/dynamic/factions/assets/send-button-arthurian.png',
    gearSlotImages: [
      { gearSlotID: 'Head', image: '/dynamic/factions/assets/gear-slot-helm-arthurian.png' },
      { gearSlotID: 'Back', image: '/dynamic/factions/assets/gear-slot-cloak-arthurian.png' },
      { gearSlotID: 'Torso', image: '/dynamic/factions/assets/gear-slot-chest-arthurian.png' },
      { gearSlotID: 'Arms', image: '/dynamic/factions/assets/gear-slot-elbows-arthurian.png' },
      { gearSlotID: 'Hands', image: '/dynamic/factions/assets/gear-slot-hands-arthurian.png' },
      { gearSlotID: 'Legs', image: '/dynamic/factions/assets/gear-slot-pants-arthurian.png' },
      { gearSlotID: 'Feet', image: '/dynamic/factions/assets/gear-slot-boots-arthurian.png' },
      { gearSlotID: 'Earring1', image: '/dynamic/factions/assets/gear-slot-rings-arthurian.png' },
      { gearSlotID: 'Earring2', image: '/dynamic/factions/assets/gear-slot-rings-arthurian.png' },
      { gearSlotID: 'Neck', image: '/dynamic/factions/assets/gear-slot-necklace-arthurian.png' },
      { gearSlotID: 'Ring1', image: '/dynamic/factions/assets/gear-slot-rings-arthurian.png' },
      { gearSlotID: 'Ring2', image: '/dynamic/factions/assets/gear-slot-rings-arthurian.png' },
      { gearSlotID: 'OneHandedWeaponLeft', image: '/dynamic/factions/assets/gear-slot-off-hand-arthurian.png' },
      { gearSlotID: 'OneHandedWeaponRight', image: '/dynamic/factions/assets/gear-slot-main-hand-arthurian.png' }
    ],
    prospectingBackgroundImage: '/dynamic/factions/assets/prospecting-background-arthurian.png',
    universalUnitFrameForegroundImage: '/dynamic/factions/assets/unit-frame-front-universal-arthurian.png',
    universalUnitFrameBackgroundImage: '/dynamic/factions/assets/unit-frame-back-universal-arthurian.png',
    arrowLeftImage: '/dynamic/factions/assets/arrow-left-arthurian.png',
    arrowPointerImage: '/dynamic/factions/assets/arrow-pointer-arthurian.png',
    buttonBackgroundImage: '/dynamic/factions/assets/button-background-arthurian.png',
    buttonBackgroundMediumImage: '/dynamic/factions/assets/button-background-med-arthurian.png',
    buttonBackgroundSmallImage: '/dynamic/factions/assets/button-background-small-arthurian.png',
    buttonSquareBackgroundImage: '/dynamic/factions/assets/button-square-arthurian.png',
    checkboxBackgroundImage: '/dynamic/factions/assets/checkbox-background-arthurian.png',
    sliderMiniImage: '/dynamic/factions/assets/slider-mini-arthurian.png',
    goldBackgroundImage: '/dynamic/factions/assets/gold-background-arthurian.png',
    dividerVerticalImage: '/dynamic/factions/assets/divider-vertical-arthurian.png',
    dividerVerticalHalfImage: '/dynamic/factions/assets/divider-vertical-half-arthurian.png',
    dividerVerticalSimpleImage: '/dynamic/factions/assets/divider-vertical-arthurian-simple.png',
    mailDividerColor: '#aaa9a9',
    mailSenderColor: '#ffc000',
    mailMessageBackgroundImage: '/dynamic/factions/assets/mail-message-background-arthurian.png',
    mailRowBackgroundImage: '/dynamic/factions/assets/mail-row-background-arthurian.png',
    mailRowPaperImage: '/dynamic/factions/assets/mail-row-paper-arthurian.png',
    selectionGlowColor: '#ffc000',
    warbandPartyBackgroundImage: '/dynamic/factions/assets/warband-party-bg-arthurian.png',
    iconArmorSaleImage: '/dynamic/factions/assets/icon-armor-sale-arthurian.png',
    iconArmorSaleLargeImage: '/dynamic/factions/assets/icon-armor-sale-large-arthurian.png',
    iconCastleImage: '/dynamic/factions/assets/icon-castle-arthurian.png',
    iconCastleLargeImage: '/dynamic/factions/assets/icon-castle-large-arthurian.png',
    iconCrownImage: '/dynamic/factions/assets/icon-crown-arthurian.png',
    iconCrownLargeImage: '/dynamic/factions/assets/icon-crown-large-arthurian.png',
    iconTutorialImage: '/dynamic/factions/assets/icon-tutorial-arthurian.png',
    iconMiscSaleImage: '/dynamic/factions/assets/icon-misc-sale-arthurian.png',
    iconMiscSaleLargeImage: '/dynamic/factions/assets/icon-misc-sale-large-arthurian.png',
    iconWeaponSaleImage: '/dynamic/factions/assets/icon-weapon-sale-arthurian.png',
    iconWeaponSaleLargeImage: '/dynamic/factions/assets/icon-weapon-sale-large-arthurian.png',
    headerBorderImage: '/dynamic/factions/assets/header-border-arthurian.png',
    headerBorderSecondaryImage: '/dynamic/factions/assets/header-border-secondary-arthurian.png',
    endcapImage: '/dynamic/factions/assets/endcap-arthurian.png',
    factionShieldImage: '/dynamic/factions/assets/faction-shield-arthurian.png',
    backgroundRealmVideo: '/dynamic/factions/assets/background-realm-arthurian.webm',
    progressBarImage: '/dynamic/factions/assets/progress-bar-fill-arthurian.png',
    progressBarCircleFillImage: '/dynamic/factions/assets/progress-bar-fill-circle-arthurian.png',
    progressBarCircleBackgroundImage: '/dynamic/factions/assets/progress-bar-background-circle-arthurian.png',
    flagBlankImage: '/dynamic/factions/assets/flag-blank-arthurian.png',
    taperBarImage: '/dynamic/factions/assets/taper-bar-arthurian.png',
    mapGlobeImage: '/dynamic/factions/assets/map-icon-globe-arthurian.png'
  }
];

export const getFactionData = (factionID: string): FactionData =>
  allFactionData.find((faction) => faction.id === factionID) ?? allFactionData[0];
